version: '3'
services:
  pipeline:
    build: ./
    command: sh -c "sleep 10s ; python3 src/components/pipeline.py" 
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456Fa$$
      - MYSQL_DATABASE=grocery_store
      
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456Fa$$
      MYSQL_DATABASE: grocery_store
    ports:
      - "3308:3306"
    volumes:
      - .grocery_store_pipeline/mysql/db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
