name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  containerize-and-run-pipeline:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ETL Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: fausstoo/grocery_store_pipeline:latest

      - name: Run ETL process in Docker container
        run: |
          docker run --rm \
            -e DB_HOST=${{ secrets.DB_HOST }}
            -e DB_USER=${{ secrets.DB_USER }}
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            -e DB_DATABASE=${{ secrets.DB_DATABASE }}
            fausstoo/grocery_store_pipeline:latest python /grocery_store_pipeline/src/components/pipeline.py
