name: CI/CD PIPELINE

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Set up MySQL Client
        run: sudo apt-get install -y default-mysql-client

      - name: Run Data Pipeline
        env:
          env:
            DB_HOST: 127.0.0.1
            DB_USERNAME: ${{ secrets.DB_USERNAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_DATABASE: ${{ secrets.DB_DATABASE }}

        run: |
          sudo /etc/init.d/mysql start
          # Connect to MySQL using mysql command
          mysql -h $DB_HOST --port ${{ secrets.DB_PORT }} -u${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e "source mysql/db_setup.sql";

          # Run your Python script after connecting to MySQL
          python src/components/pipeline.py
