name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          MYSQL_USER: ${{ secrets.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306

      python-pipeline:
        image: ./grocery_store_pipeline  # Use the path to your Dockerfile
        options: --name=python-pipeline
        ports:
          - 8000:8000  # Adjust the port mapping if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test Python App
        run: |
          cd ./grocery_store_pipeline/
          docker build -t python-pipeline .
          docker run python-pipeline
