name: Python Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: my_database
          MYSQL_USER: my_user
          MYSQL_PASSWORD: my_password
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Wait for MySQL to be ready
        run: |
          timeout=300
          while [ $timeout -gt 0 ]; do
            if mysqladmin ping --host=mysql --user=my_user --password=my_password --silent; then
              break
            fi
            sleep 1
            ((timeout--))
          done
          if [ $timeout -eq 0 ]; then
            echo "MySQL not ready within the timeout period."
            exit 1
          fi
          echo "MySQL is ready!"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Pipeline
        run: python src/components/pipeline.py
