name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  standalone-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  build-and-test:
    needs: standalone-job
    runs-on: ubuntu-latest
    
    services:
      python-pipeline:
        image: ./grocery_store_pipeline/  # Use the path to your Dockerfile
        options: --name=python-pipeline

      mysql:
        image: ./grocery_store_pipeline/mysql/  # Use the path to your MySQL Dockerfile
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
        ports:
          - 3306:3306  # Adjust the port mapping if needed
        options: --name=mysql
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test Python App
        run: |
          cd ./grocery_store_pipeline/
          docker build -t python-pipeline .
          docker run python-pipeline
