name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t grocery_store_pipeline .

      - name: Test
        run: docker run -e DB_HOST=${{ secrets.DB_HOST }} -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_PORT=3306 -e DB_DATABASE=grocery_store Dockerfile pytest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        # Add your Docker Hub repository
      - run: docker tag grocery_store_pipeline fausstoo/grocery_store_pipeline:latest
      - run: docker push fausstoo/grocery_store_pipeline:latest
