name: CI/CD PIPELINE

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Set up MySQL Client
        run: sudo apt-get install -y default-mysql-client
      - id: setup-mysql
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"

      - name: connect via unix domain socket
        run: mysql -uroot \
          --protocol=SOCKET \
          --socket=${{ steps.setup-mysql.outputs.base-dir }}/tmp/mysql.sock
          -e 'SELECT version()'

      - name: configure the root certificate for connecting via SSL/TLS.
        run: mysql -uroot \
          --ssl --ssl-mode=--ssl-mode=REQUIRED \
          --ssl-ca=${{ steps.setup-mysql.outputs.base-dir }}/var/ca.pem \
          -e 'SELECT version()'
          
      - name: Run Data Pipeline
        env:
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'localhost'
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: 3306
          DB_DATABASE: grocery_store

        run: |
          sudo apt-get install -y mysql-client
          sudo /etc/init.d/mysql start
          # Connect to MySQL using mysql command
          mysql -h $DB_HOST -u $DB_USERNAME -P $DB_PORT -e "source mysql/db_setup.sql";

          # Run your Python script after connecting to MySQL
          python src/components/pipeline.py
