name: CI/CD PIPELINE

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  
          
      - name: Run Data Pipeline
        env:
          DB_HOST: '127.0.0.1'
          DB_USERNAME: 'root'
          DB_PASSWORD: '123456Fa$$'
          DB_PORT: 3306
          DB_DATABASE: grocery_store

        run: |
          sudo apt-get install -y mysql-client
          sudo /etc/init.d/mysql start
          # Connect to MySQL using mysql command
          mysql -h $DB_HOST -u $DB_USERNAME -P $DB_PORT -e "source mysql/db_setup.sql";

          # Run your Python script after connecting to MySQL
          python src/components/pipeline.py
