name: Python Pipeline CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install MySQL client
      run: sudo apt-get install -y default-mysql-client

    - name: Install project dependencies
      run: |
        pip install -r requirements.txt
 

    - name: Set up MySQL Secrets
      env:
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    - name: Test MySQL Connection
      run: |
        mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e "SELECT 1" $MYSQL_DATABASE
        if [ $? -ne 0 ]; then
          echo "MySQL connection test failed."
          exit 1
        fi

    - name: Run Python pipeline
      run: |
        python src/components/pipeline.py