name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  db:
    image: mysql:8
    restart: always
    environment:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
    ports:
      - "3306:3306"

  containerize-pipeline:
    needs: db
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ETL Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: fausstoo/grocery_store_pipeline:latest

  run-etl-pipeline:
    needs: containerize-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Run ETL process in Docker container
        run: docker run --rm etl-image python /grocery_store_pipeline/src/components/pipeline.py