
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  services:
    python-app:
      build: ./python/
      command: sh -c "sleep 10s ; python3 ./grocery_store_pipeline/pipeline.py"
      depends_on:
        - mysql

    mysql:
      build: ./mysql/
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: ${{ secrets.DB_PORT }}
