version: '3'

services:
  python-pipeline:
    build: ./grocery_store_pipeline/pipeline_py.Dockerfile
    depends_on:
      - mysql-db
    environment:
      - DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      - MYSQL_DATABASE: grocery_store
      - DB_HOST: mysql
      - DB_USERNAME: ${{ secrets.DB_USERNAME }}
      - DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      - DB_PORT: 3306
      - DB_DATABASE: ${{ secrets.DB_DATABASE }}

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      MYSQL_DATABASE: grocery_store
