name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      python-app:
        build: ./python/
        depends_on:
          - mysql

      mysql:
        build: ./mysql/
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test Python App
        run: |
          cd ./grocery_store_pipeline/
          docker build -t python-app .
          docker run python-app
